"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](bg:bar)$username[@](fg:red bg:bar)$hostname[](fg:bar bg:blue)$directory$git_branch$git_state$git_status${custom.nogit_close}
$character"""

right_format = "$status$cmd_duration"
palette = "mine"

[palettes.mine]
bar = "#262626"
gitbg = "#2ECC71"
gitfg = "#7a0000"

[username]
show_always = true
style_user = "bg:bar fg:blue"
style_root = "bg:bar fg:red"
format = "[$user]($style)"
disabled = false

[hostname]
ssh_only = false
style = "bg:bar fg:green"
format = "[$hostname]($style)"
disabled = false

[directory]
style = "bg:blue fg:bar"
format = "[ $path ]($style)"
truncation_length = 8
truncate_to_repo = false
truncation_symbol = "…/"

[git_branch]
truncation_length = 24
truncation_symbol = "…"
symbol = ""
style = "bg:gitbg fg:bar"
format = "[](fg:blue bg:gitbg)[ $symbol $branch ]($style)"

[git_state]
style = "bg:gitbg fg:gitfg"
format = '[\($state $progress_current/$progress_total\) ]($style)'

[git_status]
style = "bg:gitbg fg:gitfg"
format = "[](fg:gitbg)"

[custom.nogit_close]
when = "! git rev-parse --is-inside-work-tree 2>/dev/null"
format = "[](fg:blue)"

[status]
disabled = false
symbol = "✖"
style = "bold red"
format = "[$symbol $status]($style)"

[cmd_duration]
style = "bold yellow"
min_time = 2_000
format = " took [$duration]($style)"

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"
