#
# Defines environment variables.
#
# Authors:
#   Bharath Kumar Ravichandran
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi


# Custom Environment Variables
export DOTDIR=~/.dotfiles
export DOTDIR_BACKUP="${DOTDIR_BACKUP:-$HOME/.dotfiles-backup}"

[[ -f "$HOME/.cargo/env" ]] && . "$HOME/.cargo/env"
