#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi


# Custom Environment Variables
export DOTDIR=~/.dotfiles
export DOTDIR_BACKUP=~/.dotfiles-backup

if [[ "$OSTYPE" == "darwin"* ]]; then
    export JAVA_HOME="/Library/Java/JavaVirtualMachines/graalvm-jdk-17.0.8+9.1/Contents/Home"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # source "$HOME/.cargo/env"
fi